# example 2: on merge to master from pull request (recommended)
name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  build:
    if: |
      github.event_name == 'pull_request' && 
      github.event.action == 'closed' && 
      github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'
        token: ${{ secrets.PAT_TOKEN }}

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.75.0
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        PRERELEASE: false
        RELEASE_BRANCHES: develop
        WITH_V: true
        DEFAULT_BUMP: minor
        GIT_API_TAGGING: false